name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  poetry-publish:
    name: Upload release to PyPI using Poetry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Poetry
      run: pip install poetry
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
    - name: Install dependencies using Poetry
      run: poetry install
    - name: Build a binary wheel and a source tarball using Poetry
      run: poetry build
    - name: Publish distribution to PyPI using Poetry
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

